### ISSUE TITLE
Error spam - NoSuchMethod

### ISSUE THREAD

**Issue by Brend-Smits** [BadgeUp/sponge-client#18] opened 2017-02-14 11:03 UTC
https://hastebin.com/ibolecizit.rb
Latest BadgeUp version
Sponge version information:
    SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-c82cd9e
    SpongeForge: 1.10.2-2221-5.1.0-BETA-2119
    Minecraft Forge: 12.18.3.2215

The error is spamming the console constantly.

**Comment by RobertHerhold** [comment] 2017-02-14 21:45
@Rubbertjuh I can't reproduce this. What other mods/plugins are you using?

EDIT: I see your network is running SkyFactory 3... it seems possible that something might be messing with my `org.json` dependency

**Comment by Brend-Smits** [comment] 2017-02-16 14:23
Sorry for the late reply. 
We are indeed running Sky Facotry 3, is there a possibility for me to debug this further?

**Comment by RobertHerhold** [comment] 2017-02-16 21:42
With such a large modpack, it's rather difficult... one thing you could do is start with just the BadgeUp plugin, and one by one, add each other plugin back and test. 

If that doesn't work you might try the same thing with the mods, but let me know before then and I'll try to help.

**Comment by RobertHerhold** [comment] 2017-02-16 23:11
@Rubbertjuh I made a [custom build](https://drive.google.com/a/badgeup.io/file/d/0B5XhYrSZDZLbM2RZOUxMUDJvYlE/view?usp=sharing) for you relocating the `org.json` dependency. Please let me know if it resolves your issue.

**Comment by RobertHerhold** [comment] 2017-02-19 20:34
@Rubbertjuh Have you gotten a chance to test out the build I linked above?

**Comment by RobertHerhold** [comment] 2017-04-14 17:48
Resolved in 381f6f9a7c82173e9a2bf9f4af908c9d9627886d

**Closed as completed by RobertHerhold** 2017-04-14 17:48 UTC
Labels: bug, can't reproduce
